view: orders {
  sql_table_name: `astrafy-take-home.dbt_emagh16web.exercise_6_orders_with_segmentation_2026` ;;

  dimension: order_id {
    primary_key: yes
    type: number
    sql: ${TABLE}.order_id ;;
    label: "Order ID"
    description: "Unique identifier of an individual order. Use this field for order-level drill-downs, not as a business KPI."
    group_label: "Order Details"
    hidden: yes
  }

  dimension: customer_id {
    type: number
    sql: ${TABLE}.customer_id ;;
    label: "Customer ID"
    description: "Unique identifier of the customer who placed the order."
    group_label: "Customer"
    synonyms: ["buyer id", "shopper id", "client id"]
  }

  dimension_group: order_date {
    type: time
    timeframes: [date, week, month, quarter, year]
    sql: ${TABLE}.order_date ;;
    label: "Order Date"
    description: "Date when the order was placed. Use this field for daily, weekly, monthly, quarterly, or yearly trend analysis."
    group_label: "Time"
  }

  dimension: order_segmentation {
    type: string
    sql: ${TABLE}.order_segmentation ;;
    label: "Customer Segment"
    description: "Segment assigned to each order using the customer's previous 12 months of purchase activity. New means 0 previous orders, Returning means 1 to 3 previous orders, and VIP means 4 or more previous orders."
    group_label: "Customer"
    synonyms: ["customer type", "customer group", "buyer segment", "shopper segment", "loyalty segment"]
  }

  measure: order_count {
    type: count
    label: "Orders"
    description: "Total number of orders in the selected period or filter context."
    group_label: "Core KPIs"
    synonyms: ["order volume", "number of orders", "orders placed"]
    drill_fields: [order_date_date, customer_id, order_segmentation]
  }

  measure: total_revenue {
    type: sum
    sql: ${TABLE}.net_sales ;;
    value_format_name: decimal_2
    label: "Revenue"
    description: "Total net sales revenue generated by orders in the selected filter context."
    group_label: "Core KPIs"
    synonyms: ["sales", "net sales", "sales revenue", "turnover"]
    drill_fields: [order_date_date, customer_id, order_segmentation]
  }

  measure: unique_customers {
    type: count_distinct
    sql: ${TABLE}.customer_id ;;
    label: "Customers"
    description: "Number of distinct customers who placed at least one order in the selected filter context."
    group_label: "Core KPIs"
    synonyms: ["unique customers", "buyers", "shoppers", "clients"]
  }

  measure: average_order_value {
    type: average
    sql: ${TABLE}.net_sales ;;
    value_format_name: decimal_2
    label: "Average Order Value"
    description: "Average net sales revenue per order. Commonly referred to as AOV."
    group_label: "Core KPIs"
    synonyms: ["AOV", "average basket value", "average purchase value"]
  }
}
