view: orders {
  sql_table_name: `astrafy-take-home.dbt_emagh16web.exercise_6_orders_with_segmentation_2026` ;;

  dimension: order_id {
    primary_key: yes
    type: number
    sql: ${TABLE}.order_id ;;
    label: "Order ID"
    description: "Unique identifier of the order."
  }

  dimension: customer_id {
    type: number
    sql: ${TABLE}.customer_id ;;
    label: "Customer ID"
    description: "Unique identifier of the customer."
  }

  dimension_group: order_date {
    type: time
    timeframes: [date, week, month, quarter, year]
    sql: ${TABLE}.order_date ;;
    label: "Order Date"
    description: "Date when the order was placed."
  }

  dimension: order_segmentation {
    type: string
    sql: ${TABLE}.order_segmentation ;;
    label: "Customer Segment"
    description: "Customer segment assigned to the order based on the customer's previous 12 months of order activity: New, Returning, or VIP."
  }

  measure: order_count {
    type: count
    label: "Orders"
    description: "Total number of orders."
    drill_fields: [order_id, order_date_date, customer_id, order_segmentation]
  }

  measure: total_revenue {
    type: sum
    sql: ${TABLE}.net_sales ;;
    value_format_name: decimal_2
    label: "Revenue"
    description: "Total net sales revenue generated by orders."
    drill_fields: [order_id, order_date_date, customer_id, order_segmentation]
  }

  measure: unique_customers {
    type: count_distinct
    sql: ${TABLE}.customer_id ;;
    label: "Customers"
    description: "Number of unique customers."
  }

  measure: average_order_value {
    type: average
    sql: ${TABLE}.net_sales ;;
    value_format_name: decimal_2
    label: "Average Order Value"
    description: "Average net sales value per order."
  }
}
